### ISSUE TITLE
Use universal-mingw32 as platform instead of CURRENT

### ISSUE THREAD

**Issue by luislavena** [bosko/gem-exefy#12]
Hello,

While testing out x64 builds of Ruby found that I'm not able to install released gem from RubyGems since it's platform is `x86-mingw32`

Found that we can avoid doing multiple releases for x86 and x64 by using `universal` platform:

```
>> a = Gem::Platform.new("universal-mingw32")
=> #<Gem::Platform:0x15ab670 @cpu="universal", @os="mingw32", @version=nil>
>> b = Gem::Platform.new "x86-mingw32"
=> #<Gem::Platform:0x15c6718 @cpu="x86", @os="mingw32", @version=nil>
>> c = Gem::Platform.new "x64-mingw32"
=> #<Gem::Platform:0x1571704 @cpu="x64", @os="mingw32", @version=nil>

>> a =~ b
=> true
>> a =~ c
=> true
```

My suggestion is change usage of `Gem::Platform::CURRENT` with `Gem::Platform.new("universal-mingw32")` (or simply `"universal-mingw32"` string.

Thoughts?

**Comment by bosko** [comment]
Thanks for looking into this. Avoiding multiple releases is always good :-) I'll check installation with "universal-mingw32" on x86 and x64 builds and change platform definition as you suggested. What do you think should I release new version (1.2.0) or we'll wait till x64 version of RubyInstaller is out? I think I should release so we have everything prepared when x64 RI is released.

**Comment by luislavena** [comment]
Thank you.

What is clone your repo, do my local changes, package the gem and install it locally instead of the release.

I think a `universal` release will be great so others can start testing this out, specially now with the automated builds available.
