### ISSUE TITLE
Hook gem install/update so exefy happens automatically?

### ISSUE THREAD

**Issue by petemounce** [bosko/gem-exefy#13]
I'd love it if it were possible to `gem install some_gem` and not need to separately run `gem exefy some_gem` afterwards to turn some_gem's executables into exe files.

I've no idea whether that's possible, though.

I'd also love for `bundle install` to do the same, so gems installed via either means will be exefy'd.

**Comment by bosko** [comment]
Gem is already working this way. If you install it prior installing other gems all gems will be "exefied". Only gems which were installed before gem-exefy must be explicitly processed.

**Comment by petemounce** [comment]
Oh!  Brilliant!
