### ISSUE TITLE
exefy + cygwin - after `exefy --all`, cygwin cannot run executables

### ISSUE THREAD

**Issue by petemounce** [bosko/gem-exefy#14]
When I run `gem exefy --all` from a windows command prompt and then any executable (eg `rake`, `gem`, `cucumber`), I get the exe resolved and it runs fine.

If I swap to a fresh cygwin prompt (which uses zsh), then I get

``` shell
~ rake --help
C:\ruby\ruby-1.9.3-p194\bin\ruby.exe: No such file or directory -- /cygdrive/c/ruby/ruby-1.9.3-p194/bin/rake (LoadError)
```

If I append .exe, it works fine:

``` shell
~ rake.exe --help                                                                                                                                                                                     
rake [-f rakefile] {options} targets...

Options are ...
    -C, --classic-namespace          Put Task and FileTask in the top level namespace
    -D, --describe [PATTERN]         Describe the tasks (matching optional PATTERN), then exit.
    -n, --dry-run                    Do a dry run without executing actions.
......
```

So, I can work around this in a few ways:
1. by defining aliases within my zshrc (or, if bash, then bashrc).
2. by setting up symlinks in my ~/bin to each of the ruby executables, eg `ln -s rake.exe ~/bin/rake` where `~/bin` is in my PATH

Can you think of anything cleaner, that lets me have the workarounds automatically applied?

Or, is there some change that can be done to gem-exefy to solve this?

(I've tried in the past to compile ruby from cygwin and use the native build (since that's what @luislavena has advised in his blog some time ago), but got too many cygwin segfaults for that to be reliable :-( ).

System: 
- gem-exefy 1.2.0
- cygwin 1.7.16.1
- Win2008R2 x64
- ruby 1.9.3-p194 & DevKit 4.5.2 from the rubyinstaller.org installers

**Comment by bosko** [comment]
Gem-exefy is not intended to be used in Cygwin same as RubyInstaller and DevKit. RubyInstaller Ruby version is compiled with MinGW tools and are not compatible with Cygwin.

**Comment by petemounce** [comment]
Oh :-(
