### ISSUE TITLE
"could not find a valid gem 'gem-exefy' (>=0) in any repository"

### ISSUE THREAD

**Issue by rpardee** [bosko/gem-exefy#15]
This is especially puzzling b/c the suggested "Possible alternative" is exactly what I specified.
I can point my browser at https://rubygems.org/gems/gem-exefy no problem.  Not behind a proxy or any such.

I'm running 64-bit windows 8.1.  Gem environment is listed below.

Many thanks!
-Roy

```
Windows PowerShell
Copyright (C) 2013 Microsoft Corporation. All rights reserved.

~> gem install gem-exefy
ERROR:  Could not find a valid gem 'gem-exefy' (>= 0) in any repository
ERROR:  Possible alternatives: gem-exefy
~> gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.3.0
  - RUBY VERSION: 1.9.3 (2014-11-13 patchlevel 551) [i386-mingw32]
  - INSTALLATION DIRECTORY: C:/programs/Ruby193/lib/ruby/gems/1.9.1
  - RUBY EXECUTABLE: C:/programs/Ruby193/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/programs/Ruby193/bin
  - SPEC CACHE DIRECTORY: C:/Users/Roy/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-mingw32
  - GEM PATHS:
     - C:/programs/Ruby193/lib/ruby/gems/1.9.1
     - C:/Users/Roy/.gem/ruby/1.9.1
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Program Files (x86)\Intel\iCLS Client\
     - C:\Program Files\Intel\iCLS Client\
     - C:\WINDOWS\system32
     - C:\WINDOWS
     - C:\WINDOWS\System32\Wbem
     - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
     - C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
     - C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
     - C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
     - C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
     - C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86
     - C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64
     - C:\Program Files (x86)\Git\cmd
     - C:\Program Files (x86)\Windows Live\Shared
     - C:\programs\Ruby193\bin
     - C:\Program Files (x86)\Git\bin
     - C:\tools\Octave-3.8.2\bin
~>
```

**Comment by bosko** [comment]
Can you tell me what is the output of:

```
gem search -r gem-exefy
```

**Comment by rpardee** [comment]
I get:

```
~> gem search -r gem-exefy
*** REMOTE GEMS ***
gem-exefy (1.2.0 universal-mingw32, 1.1.0 x86-mingw32)
~>
```

On Sun, Feb 15, 2015 at 8:02 AM, Boško Ivanišević notifications@github.com
wrote:

> Can you tell me what is the output of:
> 
> gem search -r gem-exefy
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bosko/gem-exefy/issues/15#issuecomment-74423136.

## 

Roy Pardee
http://datawranglr.com

**Comment by bosko** [comment]
Can gem be installed from regular command prompt (not PowerShell)?

**Comment by rpardee** [comment]
Ach, sorry--should have mentioned that.  Alas, no joy--cmd give the same
exact results.

I can manually download from rubygems.org & then install with "~\downloads>
gem install .\gem-exefy-1.2.0-universal-mingw32.gem"  That does work.  So
I'm set up.

Thanks for your time!

On Sun, Feb 15, 2015 at 1:57 PM, Boško Ivanišević notifications@github.com
wrote:

> Can gem be installed from regular command prompt (not PowerShell)?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bosko/gem-exefy/issues/15#issuecomment-74439433.

## 

Roy Pardee
http://datawranglr.com
