### ISSUE TITLE
exe Stubs aren't removed during a Gem uninstall

### ISSUE THREAD

**Issue by Azolo** [bosko/gem-exefy#3]
Need to figure out how to uninstall to remove the exe stubs during the Gem uninstall process.

**Comment by luislavena** [comment]
I think once gem installation is hook removal could be hooked too.

Sorry for top posting. Sent from mobile.
On Jun 9, 2012 2:20 PM, "Justin Baker" <
reply@reply.github.com>
wrote:

**Comment by bosko** [comment]
Implemented in ae54144d5
