### ISSUE TITLE
Gem installation hook is causing DevKit to be added always

### ISSUE THREAD

**Issue by luislavena** [bosko/gem-exefy#8]
Hello,

After installing `gem-exefy` locally, started to see the following behavior:

```
C:\Users\Luis\Code\luislavena\luislavena_info>gem install foreman
Fetching: foreman-0.47.0.gem (100%)
Temporarily enhancing PATH to include DevKit...
Successfully installed foreman-0.47.0
1 gem installed
```

Curious thing is that `foreman` gem doesn't have any extension in it.

This also happens when attempting to install rake or any gem that do not have extensions, even when the gemstub was already compiled

I think DevKit should be added only when gemstub is not found.

Thank you.

**Comment by bosko** [comment]
gem-exefy is triggered not on gem extensions but gem executables. Foreman has executable defined in gem specification (batch file is installed during gem installation). Same happens with any other gem (rake, bundler, etc.) with executable(s) defined in gem specification.

You are right about DevKit loading. It should be avoided if stub is found.

**Comment by luislavena** [comment]
Awesome @bosko, thank you! :heart:
